version: "3.9"

services:
  analytics-api:
    image: ${ANALYTICS_API_IMAGE}
    environment:
      - HTTP_PORT=8080
      - EVENT_QUEUE_URL=${EVENT_QUEUE_URL}
      - PLAUSIBLE_SHARED_SECRET=${PLAUSIBLE_SHARED_SECRET}
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    networks:
      - wnt_net

networks:
  wnt_net:
    external: true
