version: "3.9"

services:
  analytics-api:
    image: ${ANALYTICS_API_IMAGE}
    environment:
      - HTTP_PORT=8080
      - EVENT_QUEUE_URL=${EVENT_QUEUE_URL}
      - PLAUSIBLE_SHARED_SECRET=${PLAUSIBLE_SHARED_SECRET}
      - AWS_REGION=${AWS_REGION}
    deploy:
      labels:
        - traefik.enable=true
        # Higher priority than blog catch-all
        - traefik.http.routers.analytics.rule=Path(`/api/event`)
        - traefik.http.routers.analytics.entrypoints=web
        - traefik.http.routers.analytics.priority=100
        - traefik.http.routers.analytics.middlewares=api-event-rewrite
        - traefik.http.middlewares.api-event-rewrite.replacepath.path=/events/plausible
        - traefik.http.services.analytics.loadbalancer.server.port=8080
        # (Optional) Health check similar to HAProxy httpchk
        - traefik.http.services.analytics.loadbalancer.healthcheck.path=/healthz
        - traefik.http.services.analytics.loadbalancer.healthcheck.interval=10s
        - traefik.http.services.analytics.loadbalancer.healthcheck.timeout=2s
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    networks:
      - wnt_net

networks:
  wnt_net:
    external: true
